[package]
name = "api"
version = "0.1.0"
authors = ["hvlck <just.ethan@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "~3.3"
serde = "~1.0.126"

views = { path = "../views" }
store = { path = "../store" }
util = { path = "../util" }
